Button Group Component
AdaptiveConsulting/ui-kit-2022 pull request #223
Opened 2022-12-01 18:56 UTC by EdAdaptive

Added a new variant to the button group component called `primary`.

2022-12-01 19:57 UTC, iandilling-adaptive requested changes

2022-12-01 19:57 UTC, iandilling-adaptive commented on packages/ui-kit-theme/src/overrides/MuiButtonGroup.ts
> +        const theme = useTheme();
I'm not sure the hook should be used outside a react component. This function should accept `{ theme, ownerState}` as an argument. It's probably safer to get the theme from there.

2022-12-01 21:56 UTC, Honglin-Lu approved these changes

2022-12-01 23:44 UTC, iandilling-adaptive approved these changes

2022-12-02 00:06 UTC, wenfeng-xing approved these changes

2022-12-02 14:09 UTC, merged